version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: UTC+8
    commit-message:
      prefix: 'chore(deps): '
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: UTC+8
    commit-message:
      prefix: 'chore(deps): '
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
