#!/usr/bin/env bash

#输出当前时间
date --date='0 days ago' "+%Y-%m-%d %H:%M:%S"
echo "🔥【CI/CD】mint"

cd "/www/projects/mint"
git pull
echo "✅ 更新代码"

pnpm i && pnpm run build
if [ $? -eq 0 ]; then
    echo "✅ 编译成功"
else
    echo "❌ 编译失败"
    exit 1
fi

echo "💡 重启项目"
kill -9 $(ps -ef | grep mint | grep -v grep | awk '{print $2}')
pnpm run start