/**
 * 收集各分类下的 meta.ts，生成静态索引 pages.gen.ts（替代 require.context）。
 *
 * 仅引入 meta.ts（元数据 + 封面），不触碰 content.mdx 正文，
 * 从而让列表/SSR 组件的产物里不再夹带文章正文与内联图片。
 */
import { existsSync, writeFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import path from 'node:path';

const kRoot = process.cwd();

interface Category {
  /** 分类目录，如 app/posts */
  dir: string;
  /** 生成文件输出路径 */
  out: string;
}

const kCategories: Category[] = [
  { dir: 'app/posts', out: 'app/posts/_post/pages.gen.ts' },
  { dir: 'app/projects', out: 'app/projects/_project/pages.gen.ts' },
];

const collect = async ({ dir, out }: Category) => {
  const root = path.join(kRoot, dir);
  if (!existsSync(root)) {
    return;
  }
  const entries = await readdir(root, { recursive: true, withFileTypes: true });
  const metaFiles = entries
    .filter((e) => e.isFile() && e.name === 'meta.ts')
    .map((e) => path.join(e.parentPath, e.name))
    .sort();

  const outDir = path.dirname(path.join(kRoot, out));
  const imports: string[] = [];
  const items: string[] = [];
  metaFiles.forEach((file, i) => {
    const pageDir = path.dirname(file);
    // 路由路径：相对 app/ 去掉前缀，如 /posts/2022/chatgpt
    const route = `/${path.relative(path.join(kRoot, 'app'), pageDir)}`;
    // 从生成文件位置到 meta.ts 的相对引入说明符
    let spec = path.relative(outDir, file).replace(/\.ts$/, '');
    if (!spec.startsWith('.')) {
      spec = `./${spec}`;
    }
    imports.push(`import { metadata as m${i} } from '${spec}';`);
    items.push(`  { path: '${route}', ...m${i} },`);
  });

  const content = `// AUTO-GENERATED by scripts/collect.ts — do not edit.
${imports.join('\n')}

export const pages = [
${items.join('\n')}
];
`;
  writeFileSync(path.join(kRoot, out), content);
  console.log(`✅ ${out} (${metaFiles.length} pages)`);
};

const main = async () => {
  for (const category of kCategories) {
    await collect(category);
  }
};

main();
