#!/usr/bin/env bash

for i in "$@"; do
    if ! [ -n "$command_" ] ; then
        command_=$i
    else
        if ! [ -n "$commands_" ] ; then
            commands_=($i)
        else
            commands_+=($i)
        fi
    fi
done

if [ -n "$command_" ] ; then
    npx tsx ${command_} ${commands_[*]}
fi